<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationIcon>MEMENTO.ico</ApplicationIcon>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MetadataExtractor" Version="2.9.3" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.7" />
		<PackageReference Include="TagLibSharp" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Fonts\Smiley Sans.ttf" />
	</ItemGroup>

</Project>